learning_log/learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
     path('admin/', admin.site.urls),
     path('users/', include('users.urls')),
     path('', include('learning_logs.urls'))
]

learning_log/learning_logs/urls.py
from django.urls import path
from .views import index, topics, topic, new_topic, new_entry, edit_entry

app_name = 'learning_logs'
urlpatterns = [
     path('', index, name='index'),
     path('topics/', topics, name='topics'),
     path('topics/<int:topic_id>/', topic, name='topic'),
     path('new_topic/', new_topic, name='new_topic'),
     path('new_entry/<int:topic_id>/', new_entry, name='new_entry'),
     path('edit_entry/<int:entry_id>/', edit_entry, name='edit_entry'),
]

learning_log/users/urls.py
from django.urls import path, include
from . import views

app_name = 'users'

urlpatterns = [
    path('', include('django.contrib.auth.urls')),
    path('register/', views.register, name='register'),
]

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

class Topic(models.Model):
     text = models.CharField(max_length=200)
     date_added = models.DateTimeField(auto_now_add=True)
     owner = models.ForeignKey(User, on_delete=models.CASCADE)

     def __str__(self):
         return self.text

class Entry(models.Model):
     topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
     text = models.TextField()
     date_added = models.DateTimeField(auto_now_add=True)
    
     class Meta:
         verbose_name_plural = 'entries'
    
     def __str__(self):
         return f"{self.text[:50]}..."

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry 

class TopicForm(forms.ModelForm):
    
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):

    class Meta:
    
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_log/learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm
from django.http import Http404

def index(request):
     return render(request, 'learning_logs/index.html')

@login_required
def topics(request):
     topics = Topic.objects.filter(owner=request.user).order_by('date_added')
     context = {'topics': topics}
     return render(request, 'learning_logs/topics.html', context)

@login_required
@login_required
def topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
                new_entry = form.save(commit=False)
                new_entry.topic = topic
                new_entry.save()
        return redirect('learning_logs:topic', topic_id=topic_id)
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

learning_log/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            login(request, new_user)
            return redirect('learning_logs:index')
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_log/templates/learning_logs/base.html
<!DOCTYPE html>
<html lang="en">
    
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Learning Log</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>   
    </head>

    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid bg-primary text-white rounded">
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Learning Log</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'learning_logs:topics' %}">Topics</a>
                    </li>
                </ul>
                <div class="d-flex ms-auto">
                    <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                        <span class="navbar-text">Hello, {{ user.username }}</span>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">log out</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:login' %}">log in</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                        </li>
                    {% endif %}  
                    </ul>
                </div>
            </div>
        </div>
    </nav>


    {% block content %}
    {% endblock %}


</html>

learning_log/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Edit entry:</p>
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">save changes</button>
    </form>
{% endblock content %}

learning_log/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <div class="container">
        <div class="mt-4 p-5 bg-primary text-white rounded">
            <h1>Track your learning.</h1> 
        </div>
        <h6>
        <a href="{% url 'users:register' %}">Register an account</a> to make
        your own Learning Log, and list the topics you're learning about.
        </h6>
        <h6>
        Whenever you learn something new about a topic, make an entry 
        summarizing what you've learned.
        </h6>
    </div>
{% endblock content %}

learning_log/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% block content %}
    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
    <p>Add a new entry:</p>
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name='submit'>add entry</button>
    </form>
{% endblock content %}

learning_log/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <p>Add a new topic:</p>
    <form action="{% url 'learning_logs:new_topic' %}" method='post' class="mx-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button name="submit" type="submit" class="btn btn-dark mt-2">add topic</button>
    </form>
{% endblock content %}

learning_log/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <div class='container'>
        <h1><p>Topic: {{topic}}</p></h1>

        <p>Entries: <a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a> </p>

            {% for entry in entries %}
                <div class="card mb-2">
                    <div class="card-header">
                        {{entry.date_added|date:'M d, Y H:i'}}
                    </div>
                    <div class="card-body">
                        {{entry.text|linebreaks}}
                        <p><a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a></p>
                    </div>
                </div>
            {% empty %}
                No entries
            {% endfor %}
    </div>
{% endblock content %}

learning_log/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}
    <div class='container'>
        <h1><p>Topics</p></h1>
        <ul>
            {% for topic in topics %}
                <li><h3><a href="{% url 'learning_logs:topic' topic.id %}" class="fw-lighter nav-link">{{topic}}</a></h3></li>
            {% empty %}
                <li> No topics </li>
            {% endfor %}
        </ul>
        <h3><a href="{% url 'learning_logs:new_topic' %}" class="btn-link ">Add a new topic:</a></h3>
    </div>
{% endblock content %}